name: Tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
    name: Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - run: pip install -e .
    - run: pip install pytest-cov
    - run: pytest --cov ./pytest_expectdir --cov-report=xml
    - uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        files: ./coverage.xml # optional
        name: pytest-expectdir@python${{ matrix.python-version }}
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
